trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
# Step 1: Install Python
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true

# Step 2: Install dependencies
- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install Python Dependencies'

# Step 3: Debug Directory Structure (Optional)
- script: |
    ls -R Python_NeetCode_150
  displayName: 'List Files in Python_NeetCode_150'

# Step 4: Run Tests
- script: |
    python -m unittest discover -s Python_NeetCode_150 -p "test_*.py"
  displayName: 'Run Unit Tests'

# Step 5: Publish Test Results (Optional)
- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/test-results.xml'
    failTaskOnFailedTests: true
