trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true

- script: |
    python -m pip install --upgrade pip
    pip install pytest
  displayName: 'Set up Python environment'

- script: |
    pytest neetcode-150
  displayName: 'Run Tests'
