trigger:
- main  # Adjust the branch name as needed

pool:
  vmImage: 'ubuntu-latest'  # Use 'windows-latest' if working on Windows

steps:
# Step 1: Install Python
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'  # Use the desired Python version
    addToPath: true

# Step 2: Install dependencies (if you have a requirements.txt)
- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install Python Dependencies'

# Step 3: Run Tests
- script: |
    python -m unittest discover -s Python_NeetCode_150 -p "test_*.py"
  displayName: 'Run Unit Tests'

# Step 4: Publish Test Results (optional)
- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/test-results.xml'
    failTaskOnFailedTests: true
